"""Add customer and update relationships

Revision ID: 521aff0f11cd
Revises: 
Create Date: 2024-06-19 15:38:53.630482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521aff0f11cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sales_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_sales_calls_customer_id_customers')),
    sa.ForeignKeyConstraint(['rating_id'], ['ratings.id'], name=op.f('fk_sales_calls_rating_id_ratings')),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], name=op.f('fk_sales_calls_stage_id_stages')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sales_calls_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('sales_call_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_opportunities_customer_id_customers')),
    sa.ForeignKeyConstraint(['sales_call_id'], ['sales_calls.id'], name=op.f('fk_opportunities_sales_call_id_sales_calls')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_opportunity',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_opportunity_customer_id_customers')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_customer_opportunity_opportunity_id_opportunities')),
    sa.PrimaryKeyConstraint('customer_id', 'opportunity_id')
    )
    op.create_table('user_opportunity',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_user_opportunity_opportunity_id_opportunities')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_opportunity_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'opportunity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_opportunity')
    op.drop_table('customer_opportunity')
    op.drop_table('opportunities')
    op.drop_table('sales_calls')
    op.drop_table('users')
    op.drop_table('stages')
    op.drop_table('ratings')
    op.drop_table('customers')
    # ### end Alembic commands ###
